<#
    .SYNOPSIS
        Copies any Wiki files from the module into the Wiki and optionally overwrite
        any existing files.

    .PARAMETER Path
        The path to the output that was generated by New-DscResourceWikiPage.

    .PARAMETER DestinationPath
        The destination path for the Wiki files.

    .PARAMETER WikiSourcePath
        The name of the folder that contains the source Wiki files.

    .EXAMPLE
        Copy-WikiFolder -Path '.\output\WikiContent' -DestinationPath 'c:\repoName.wiki.git' -WikiSourcePath '.\source\WikiSource'

        Copies any Wiki files from the module into the Wiki.
#>
function Copy-WikiFolder
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory = $true)]
        [System.String]
        $Path,

        [Parameter(Mandatory = $true)]
        [System.String]
        $DestinationPath,

        [Parameter()]
        [System.String]
        $WikiSourcePath,

        [Parameter()]
        [System.Management.Automation.SwitchParameter]
        $Force
    )

    $pathsToCopy = @($Path)

    if ($PSBoundParameters.ContainsKey('WikiSourcePath'))
    {
        $pathsToCopy += $WikiSourcePath
    }

    Write-Verbose -Message ($localizedData.CopyWikiFoldersMessage -f ($pathsToCopy -join ''', '''))

    $wikiFiles = Get-ChildItem -Path $pathsToCopy

    foreach ($file in $wikiFiles)
    {
        Write-Verbose -Message ($localizedData.CopyFileMessage -f $file.Name)

        Copy-Item -Path $file.FullName -Destination $DestinationPath -Force:$Force
    }
}
